const text = {
  logo: { en: "CRM PANEL", fa: "پنل مدیریت" },
  welcome: { en: "Welcome", fa: "خوش آمدید" },
  logout: { en: "log out", fa: "خروج" },
  login: { en: "login", fa: "ورود" },
  login_form: { en: "login form", fa: "فرم ورود" },
  register: { en: "register", fa: "ثبت نام" },
  register_form: { en: "register form", fa: "فرم ثبت نام" },
  lang: { en: "en", fa: "فارسی" },
  form: { en: "Form", fa: "فرم" },
  have_account: { en: "have Account", fa: "اکانت دارید" },
  havent_account: { en: " not have Account", fa: "اکانت ندارید" },
  homePage_title: { en: "Welcome to CRM Panel", fa: "به پنل مدیریت خوش آمدید" },
  pickDate: { en: "birthday", fa: "تاریخ تولد" },
  homePage_text: {
    en: "To manage your costumers, please register or login to your account.",
    fa: "برای مدیریت مشتریانتان ، لطفا ثبت نام یا ورود کنید",
  },
  footer: {
    en: "Next Project | CRM Project ©",
    fa: "پروژه نکست | مدیریت مشتری",
  },
  number: { en: "no.", fa: "شماره" },
  email: { en: "email", fa: "ایمیل" },
  password: { en: "password", fa: "رمز عبور" },
  delete: { en: "delete", fa: "حذف" },
  edit: { en: "edit", fa: "ویرایش" },
  details: { en: "details", fa: "جزئیات" },
  add_costumer: { en: "add costumer", fa: "افزودن مشتری" },
  details_page: { en: "details page", fa: "صفحه جزئیات" },
  edit_page: { en: "edit page", fa: "صفحه ویرایش" },
  no_costumer: { en: "no costumer yet ...", fa: "فعلا مشتری وجود ندارد" },
  name: { en: " name", fa: "نام" },
  first_name: { en: "first name", fa: "نام" },
  last_name: { en: "last name", fa: "نام خانوادگی" },
  city: { en: "city", fa: "شهر" },
  phone: { en: "phone", fa: "تلفن" },
  purchased_items: { en: "purchased items", fa: "موارد خریداری شده " },
  item: { en: "item", fa: "آیتم" },
  price: { en: "price", fa: "قیمت" },
  product: { en: "product", fa: "محصول" },
  updated_at: { en: "updated at", fa: "بروزرسانی در" },
  qty: { en: "qty", fa: "تعداد" },
  add: { en: "add", fa: "افزودن" },
  remove: { en: "remove", fa: "حذف" },
  save: { en: "save", fa: "ذخیره" },
  cancel: { en: "cancel", fa: "انصراف" },
};

export default text;
