const text = {
  logo: { en: "CRM PANEL", fa: "پنل مدیریت" },
  welcome: { en: "Welcome", fa: "خوش آمدید" },
  login: { en: "login", fa: "ورود" },
  logout: { en: "log out", fa: "خروج" },
  register: { en: "register", fa: "ثبت نام" },
  lang: { en: "en", fa: "فارسی" },
  form: { en: "Form", fa: "فرم" },
  form_text: { en: "have Account", fa: "اکانت دارید" },
  homePage_title: { en: "Welcome to CRM Panel", fa: "به پنل مدیریت خوش آمدید" },
  homePage_text: {
    en: "To manage your costumers, please register or login to your account.",
    fa: "برای مدیریت مشتریانتان ، لطفا ثبت نام یا ورود کنید",
  },
  footer: {
    en: "Next Project | CRM Project ©",
    fa: "پروژه نکست | مدیریت مشتری",
  },
  email: { en: "email", fa: "ایمیل" },
  password: { en: "password", fa: "رمز عبور" },
  delete: { en: "delete", fa: "حذف" },
  edit: { en: "edit", fa: "ویرایش" },
  details: { en: "details", fa: "جزِئیات" },
  add_costumer: { en: "add costumer", fa: "افزودن مشتری" },
  page: { en: "page", fa: "صفحه" },
  name: { en: " name", fa: "نام" },
  first_name: { en: "first name", fa: "نام" },
  last_name: { en: "last name", fa: "نام خانوادگی" },
  city: { en: "city", fa: "شهر" },
  phone: { en: "phone", fa: "تلقن" },
  purchased: { en: "purchased ", fa: "خریداری شده" },
  items: { en: "items", fa: "موارد" },
  item: { en: "item", fa: "مورد" },
  price: { en: "price", fa: "قیمت" },
  qty: { en: "qty", fa: "تعداد" },
  add: { en: "add", fa: "افزودن" },
  remove: { en: "remove", fa: "حذف" },
  save: { en: "save", fa: "ذخیره" },
  cancel: { en: "cancel", fa: "انصراف" },
};

export default text;
